/*
 * hv_cathode.c
 *
 *  Created on: Aug 1, 2019
 *      Author: alx
 */
#include "xparameters.h"
#include "hv_cathode.h"
#include "xil_types.h"



void TestEC_sig()
{
	*(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGW_HVCATH_STIM_EC_SIG) = 5;
	*(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGW_HVCATH_STIM_EC_SIG) = 0;
}

void CathodeSetAutoMode(int mode) //1 or 0
{
	*(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGW_HVCATH_OPT) = mode*(1<<BIT_ADCV_EN);
}

void ResetADCV()
{
	*(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGW_HVCATH_CTRL) = (1<<BIT_ADCV_RESET);
	*(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGW_HVCATH_CTRL) = 0;
}

void ConfADCV()
{
	ResetADCV();
	*(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGW_HVCATH_EN_EC) = 0x1FF;
	*(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGW_HVCATH_RELEASE_TIME) = 1000;
	*(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGW_HVCATH_GTU_LEN0) = 3;
	*(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGW_HVCATH_GTU_LEN1) = 4;
	*(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGW_HVCATH_BIG_PULSES_NUM) = 5;
}

u32 GetADCVEcTimer()
{
	return *(u32*)(XPAR_AXI_CATHODE_CTRL_0_BASEADDR + 4*REGR_HVCATH_GET_EC0_TIMER);
}

