#set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/pass_intr]

##set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/m_axis_tvalid_key]
##set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/m_axis_tlast_key]
##set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/m_axis_tready_key]
##set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/m_axis_tready_sink]
#set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/pass]
#set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/pass_tlast]
#set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/periodic_trig]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[0]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[10]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[11]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[12]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[13]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[14]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[15]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[1]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[2]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[3]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[4]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[5]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[6]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[7]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[8]}]
##set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_cnt_reg[9]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state[0]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state[1]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state[2]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state[3]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state_sink[0]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state_sink[1]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state_sink[2]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state_sink[3]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/tlast_remover_cnt[0]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/tlast_remover_cnt[1]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/tlast_remover_cnt[2]}]
#set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/fifo_half]
##set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig]
##set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/s_axis_tlast]
##set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/s_axis_tvalid]
#set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_latch]
#set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_latch_clr]


#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[0]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[10]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[11]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[12]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[13]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[14]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[15]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[16]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[17]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[18]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[19]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[1]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[20]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[21]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[22]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[23]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[24]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[25]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[26]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[27]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[28]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[29]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[2]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[30]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[31]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[3]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[4]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[5]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[6]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[7]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[8]}]
#set_property MARK_DEBUG true [get_nets {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[9]}]
#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 3 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/tlast_remover_cnt[0]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/tlast_remover_cnt[1]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/tlast_remover_cnt[2]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 4 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state_sink[0]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state_sink[1]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state_sink[2]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state_sink[3]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
#set_property port_width 4 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state[0]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state[1]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state[2]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/sm_state[3]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 32 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[0]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[1]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[2]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[3]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[4]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[5]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[6]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[7]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[8]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[9]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[10]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[11]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[12]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[13]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[14]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[15]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[16]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[17]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[18]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[19]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[20]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[21]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[22]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[23]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[24]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[25]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[26]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[27]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[28]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[29]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[30]} {design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/gtu_sig_counter[31]}]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 1 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/fifo_half]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 1 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/pass]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
#set_property port_width 1 [get_debug_ports u_ila_0/probe6]
#connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/pass_tlast]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
#set_property port_width 1 [get_debug_ports u_ila_0/probe7]
#connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/periodic_trig]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
#set_property port_width 1 [get_debug_ports u_ila_0/probe8]
#connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_latch]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
#set_property port_width 1 [get_debug_ports u_ila_0/probe9]
#connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/axis_flow_control_D1/U0/i_flow_control_d1/trig_latch_clr]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
