set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/mem_doutb[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/mem_doutb[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/mem_doutb[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/mem_doutb[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[7]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_2/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[0]} {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[1]} {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[2]} {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[3]} {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[4]} {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[5]} {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[6]} {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/raw_datapath_gen[2].counter_reg__0[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/mem_doutb[8]} {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/mem_doutb[9]} {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/mem_doutb[10]} {design_1_i/axi_data_provider_0/U0/axi_data_provider_v1_0_S00_AXI_inst/i_data_provider/mem_doutb[11]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
