set_property MARK_DEBUG true [get_nets design_1_i/axi_data_provider_0_m_axis_art0l_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axi_data_provider_0_m_axis_art0l_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axi_data_provider_0_m_axis_art0l_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r1_M00_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r1_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r1_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r1_M01_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r1_M01_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r1_M01_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_clock_converter_0_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_clock_converter_0_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_clock_converter_0_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_0_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_0_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_0_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r10_M00_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r10_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r10_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r10_M01_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r10_M01_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r10_M01_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_combiner_0_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_combiner_0_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L6_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L6_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L6_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/scurve_adder_0_out_stream_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/scurve_adder_0_out_stream_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/scurve_adder_0_out_stream_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r_M00_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r_M01_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r_M01_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r_M01_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_switch_0_M00_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_switch_0_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_switch_0_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L2_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L2_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L2_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/L2triggerv5_0_out_stream_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/L2triggerv5_0_out_stream_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/L2triggerv5_0_out_stream_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L2b_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L2b_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L2b_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_1_m_axis_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_1_m_axis_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_1_m_axis_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_6_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_6_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_6_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_7_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_7_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_7_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L9_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L9_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L9_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/top_switch_0_m_axis_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/top_switch_0_m_axis_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/top_switch_0_m_axis_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_0_m_axis_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_0_m_axis_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_flow_control_0_m_axis_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_6_M_AXIS_1_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_6_M_AXIS_1_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_6_M_AXIS_1_TVALID]


set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_L1_s2mm_introut]
set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_L2_s2mm_introut]
set_property MARK_DEBUG true [get_nets design_1_i/axi_dma_raw_s2mm_introut]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list design_1_i/axi_data_provider_0_m_axis_art0l_TLAST]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list design_1_i/axi_dma_raw_s2mm_introut]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/axi_data_provider_0_m_axis_art0l_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/axi_data_provider_0_m_axis_art0l_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/axi_dma_L1_s2mm_introut]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/axi_dma_L2_s2mm_introut]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axis_broadcaster_1r1_M00_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axis_broadcaster_1r1_M00_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axis_broadcaster_1r1_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/axis_broadcaster_1r1_M01_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/axis_broadcaster_1r1_M01_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/axis_broadcaster_1r1_M01_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/axis_broadcaster_1r_M00_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/axis_broadcaster_1r_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/axis_broadcaster_1r_M01_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/axis_broadcaster_1r_M01_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/axis_broadcaster_1r_M01_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/axis_data_fifo_6_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/axis_data_fifo_6_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/axis_data_fifo_6_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/axis_data_fifo_fc_L2_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list design_1_i/axis_data_fifo_fc_L2_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/axis_data_fifo_fc_L2_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/axis_data_fifo_fc_L2b_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/axis_data_fifo_fc_L2b_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/axis_data_fifo_fc_L2b_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/axis_data_fifo_fc_L6_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/axis_data_fifo_fc_L6_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/axis_data_fifo_fc_L6_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/axis_flow_control_1_m_axis_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list design_1_i/axis_flow_control_1_m_axis_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list design_1_i/axis_switch_0_M00_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list design_1_i/axis_switch_0_M00_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list design_1_i/axis_switch_0_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list design_1_i/L2triggerv5_0_out_stream_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list design_1_i/L2triggerv5_0_out_stream_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list design_1_i/L2triggerv5_0_out_stream_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list design_1_i/scurve_adder_0_out_stream_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list design_1_i/scurve_adder_0_out_stream_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list design_1_i/scurve_adder_0_out_stream_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list design_1_i/axis_broadcaster_1r10_M00_AXIS_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list design_1_i/axis_broadcaster_1r10_M00_AXIS_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list design_1_i/axis_broadcaster_1r10_M00_AXIS_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list design_1_i/axis_broadcaster_1r10_M01_AXIS_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list design_1_i/axis_broadcaster_1r10_M01_AXIS_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list design_1_i/axis_broadcaster_1r10_M01_AXIS_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list design_1_i/axis_clock_converter_0_M_AXIS_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list design_1_i/axis_clock_converter_0_M_AXIS_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list design_1_i/axis_clock_converter_0_M_AXIS_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list design_1_i/axis_combiner_0_M_AXIS_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe11]
set_property port_width 1 [get_debug_ports u_ila_1/probe11]
connect_debug_port u_ila_1/probe11 [get_nets [list design_1_i/axis_data_fifo_6_M_AXIS_1_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe12]
set_property port_width 1 [get_debug_ports u_ila_1/probe12]
connect_debug_port u_ila_1/probe12 [get_nets [list design_1_i/axis_data_fifo_6_M_AXIS_1_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe13]
set_property port_width 1 [get_debug_ports u_ila_1/probe13]
connect_debug_port u_ila_1/probe13 [get_nets [list design_1_i/axis_data_fifo_6_M_AXIS_1_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe14]
set_property port_width 1 [get_debug_ports u_ila_1/probe14]
connect_debug_port u_ila_1/probe14 [get_nets [list design_1_i/axis_data_fifo_fc_L9_M_AXIS_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe15]
set_property port_width 1 [get_debug_ports u_ila_1/probe15]
connect_debug_port u_ila_1/probe15 [get_nets [list design_1_i/axis_data_fifo_fc_L9_M_AXIS_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe16]
set_property port_width 1 [get_debug_ports u_ila_1/probe16]
connect_debug_port u_ila_1/probe16 [get_nets [list design_1_i/axis_data_fifo_fc_L9_M_AXIS_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe17]
set_property port_width 1 [get_debug_ports u_ila_1/probe17]
connect_debug_port u_ila_1/probe17 [get_nets [list design_1_i/axis_dwidth_converter_0_M_AXIS_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe18]
set_property port_width 1 [get_debug_ports u_ila_1/probe18]
connect_debug_port u_ila_1/probe18 [get_nets [list design_1_i/axis_dwidth_converter_0_M_AXIS_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe19]
set_property port_width 1 [get_debug_ports u_ila_1/probe19]
connect_debug_port u_ila_1/probe19 [get_nets [list design_1_i/axis_dwidth_converter_0_M_AXIS_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe20]
set_property port_width 1 [get_debug_ports u_ila_1/probe20]
connect_debug_port u_ila_1/probe20 [get_nets [list design_1_i/axis_dwidth_converter_7_M_AXIS_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe21]
set_property port_width 1 [get_debug_ports u_ila_1/probe21]
connect_debug_port u_ila_1/probe21 [get_nets [list design_1_i/axis_dwidth_converter_7_M_AXIS_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe22]
set_property port_width 1 [get_debug_ports u_ila_1/probe22]
connect_debug_port u_ila_1/probe22 [get_nets [list design_1_i/axis_dwidth_converter_7_M_AXIS_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe23]
set_property port_width 1 [get_debug_ports u_ila_1/probe23]
connect_debug_port u_ila_1/probe23 [get_nets [list design_1_i/axis_flow_control_0_m_axis_TREADY]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe24]
set_property port_width 1 [get_debug_ports u_ila_1/probe24]
connect_debug_port u_ila_1/probe24 [get_nets [list design_1_i/axis_flow_control_0_m_axis_TVALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe25]
set_property port_width 1 [get_debug_ports u_ila_1/probe25]
connect_debug_port u_ila_1/probe25 [get_nets [list design_1_i/top_switch_0_m_axis_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe26]
set_property port_width 1 [get_debug_ports u_ila_1/probe26]
connect_debug_port u_ila_1/probe26 [get_nets [list design_1_i/top_switch_0_m_axis_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_FCLK_CLK0]
