set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L14_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L14_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L12_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L13_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L13_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L9_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/top_switch_0_m_axis_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L10_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L11_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L11_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L11_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/top_switch_0_m_axis_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L14_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/top_switch_0_m_axis_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L10_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L12_M_AXIS_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L13_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L12_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L10_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L9_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_data_fifo_fc_L9_M_AXIS_TVALID]

set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r10_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r10_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r10_M01_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r11_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r11_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r11_M01_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r12_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r12_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r12_M01_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r13_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r13_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r13_M01_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r14_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r14_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r14_M01_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r15_M00_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r15_M00_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_broadcaster_1r15_M01_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_0_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_0_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_2_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_2_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_3_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_3_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_4_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_4_M_AXIS_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_5_M_AXIS1_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_5_M_AXIS1_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_6_M_AXIS_TREADY]
set_property MARK_DEBUG true [get_nets design_1_i/axis_dwidth_converter_6_M_AXIS_TVALID]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list design_1_i/axis_broadcaster_1r10_M00_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list design_1_i/axis_broadcaster_1r10_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/axis_broadcaster_1r10_M01_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/axis_broadcaster_1r11_M00_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/axis_broadcaster_1r11_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/axis_broadcaster_1r11_M01_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_i/axis_broadcaster_1r12_M00_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axis_broadcaster_1r12_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/axis_broadcaster_1r12_M01_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/axis_broadcaster_1r13_M00_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/axis_broadcaster_1r13_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/axis_broadcaster_1r13_M01_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/axis_broadcaster_1r14_M00_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/axis_broadcaster_1r14_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/axis_broadcaster_1r14_M01_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/axis_broadcaster_1r15_M00_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/axis_broadcaster_1r15_M00_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/axis_broadcaster_1r15_M01_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list design_1_i/axis_data_fifo_fc_L9_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/axis_data_fifo_fc_L9_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list design_1_i/axis_data_fifo_fc_L9_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/axis_data_fifo_fc_L10_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/axis_data_fifo_fc_L10_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/axis_data_fifo_fc_L10_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/axis_data_fifo_fc_L11_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/axis_data_fifo_fc_L11_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/axis_data_fifo_fc_L11_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/axis_data_fifo_fc_L12_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/axis_data_fifo_fc_L12_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list design_1_i/axis_data_fifo_fc_L12_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list design_1_i/axis_data_fifo_fc_L13_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list design_1_i/axis_data_fifo_fc_L13_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list design_1_i/axis_data_fifo_fc_L13_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list design_1_i/axis_data_fifo_fc_L14_M_AXIS_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list design_1_i/axis_data_fifo_fc_L14_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list design_1_i/axis_data_fifo_fc_L14_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list design_1_i/axis_dwidth_converter_0_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list design_1_i/axis_dwidth_converter_0_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list design_1_i/axis_dwidth_converter_2_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list design_1_i/axis_dwidth_converter_2_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list design_1_i/axis_dwidth_converter_3_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list design_1_i/axis_dwidth_converter_3_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list design_1_i/axis_dwidth_converter_4_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list design_1_i/axis_dwidth_converter_4_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list design_1_i/axis_dwidth_converter_5_M_AXIS1_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list design_1_i/axis_dwidth_converter_5_M_AXIS1_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list design_1_i/axis_dwidth_converter_6_M_AXIS_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
connect_debug_port u_ila_0/probe47 [get_nets [list design_1_i/axis_dwidth_converter_6_M_AXIS_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
connect_debug_port u_ila_0/probe48 [get_nets [list design_1_i/top_switch_0_m_axis_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
connect_debug_port u_ila_0/probe49 [get_nets [list design_1_i/top_switch_0_m_axis_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
connect_debug_port u_ila_0/probe50 [get_nets [list design_1_i/top_switch_0_m_axis_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
